twig:
    file_name_pattern: '*.twig'
    date:
        timezone: 'Europe/Paris'
    globals:
        card_booking: '@App\Service\CardBooking'
        feature_flags: '@App\Service\FeatureFlags'

when@test:
    twig:
        strict_variables: true
