<?php

return [
    'theme_assets_url' => './',
    'css_files' => [
        './css/bootstrap.min.css',
        './css/owl.carousel.min.css',
        './css/owl.theme.default.min.css',
        './css/animate.css',
        './css/magnific-popup.css',
        './css/datetimepicker.min.css',
        './css/flaticon.css',
        './css/theme.css',
        './css/menu.css',
        './css/style.css',
        './css/zefix-anim.css',
        './css/zresponsive.css',
    ],
    'js_files' => [
        './js/jquery-3.7.0.min.js',
        './js/popper.min.js',
        './js/bootstrap.min.js',
        './js/modernizr.custom.js',
        './js/jquery.easing.js',
        './js/jquery.validate.min.js',
        './js/jquery.magnific-popup.min.js',
        './js/jquery.ajaxchimp.min.js',
        './js/owl.carousel.min.js',
        './js/datetimepicker.js',
        './js/wow.js',
        './js/materialize.js',
        './js/tweenmax.min.js',
        './js/menu.js',
        './js/theme.js',
        './js/slideshow.js',
        './js/custom.js',
        './js/booking-form.js',
        './js/contact-form.js',
        './js/comment-form.js',
        './js/request-form.js',
    ],
];
